# Generated by Django 5.0.6 on 2024-05-12 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0003_price_card_illustration"),
        ("exchange", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchangeprovider",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="cardconnection",
            name="card_illustration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="connections",
                to="card.cardillustration",
            ),
        ),
    ]
