# Generated by Django 5.0.6 on 2024-09-24 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0004_providerworker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providerworker",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="worker",
                to="exchange.exchangeprovider",
            ),
        ),
    ]
