version: "3.12"
services:
  api:
    build: .
    volumes:
      - ./src:/usr/app
    ports:
      - "8000:8000"
    networks:
      - backend
    environment:
      ENV: development
    healthcheck:
      test: curl -f http://127.0.0.1:8000/health_check/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14-bullseye
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - ./docker/db/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend:

volumes:
  pg_data: