version: "3.4"
services:
  api:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      ENV: development
    healthcheck:
      test: curl -f http://127.0.0.1:8000/health_check/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 10s
      timeout: 5s
      retries: 5