# Generated by Django 5.0.6 on 2024-05-10 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="art_type",
        ),
    ]
