# Generated by Django 5.0.6 on 2024-05-10 17:59

import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0002_remove_card_art_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="card",
            name="crew",
        ),
        migrations.AlterField(
            model_name="cardimage",
            name="src",
            field=sorl.thumbnail.fields.ImageField(max_length=255, upload_to="img/"),
        ),
        migrations.AddField(
            model_name="card",
            name="crew",
            field=models.ManyToManyField(related_name="crews", to="card.crew"),
        ),
    ]
