# Generated by Django 5.0.6 on 2024-05-12 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0002_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="card_illustration",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="card.cardillustration",
            ),
            preserve_default=False,
        ),
    ]
