# Generated by Django 5.0.6 on 2024-09-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0004_alter_price_card_illustration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
