# Generated by Django 5.0.6 on 2024-10-20 14:03

import django.db.models.deletion
import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0005_alter_price_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Atribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "src",
                    sorl.thumbnail.fields.ImageField(max_length=255, upload_to="img/"),
                ),
                ("alt", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("logo", models.ImageField(upload_to="atributes")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="cardillustration",
            name="external_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="rare",
            field=models.CharField(
                choices=[
                    ("C", "Common"),
                    ("UC", "Uncommon"),
                    ("R", "Rare"),
                    ("SR", "Super Rare"),
                    ("SCR", "Secret Rare"),
                    ("L", "Leader"),
                    ("SP CARD", "Special Card"),
                    ("SEC", "SEC"),
                ],
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="trigger",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="attribute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="atributes",
                to="card.atribute",
            ),
        ),
    ]
