# Generated by Django 5.0.6 on 2024-10-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0006_atribute_cardillustration_external_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardillustration",
            name="code",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
