# Generated by Django 5.0.6 on 2024-05-11 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("card", "0002_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="ALigaOnePiecePrice",
            fields=[
                (
                    "price_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="card.price",
                    ),
                ),
            ],
            bases=("card.price",),
        ),
    ]
