# Generated by Django 5.0.6 on 2024-05-12 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0003_price_card_illustration"),
        ("exchange_aligaonepiece", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ALigaOnePiecePrice",
            new_name="ProviderPrice",
        ),
    ]
